classDiagram
    class Учасник обслуговування {
    }

    class Бронювання {
        <<interface>>
        +зробити замовлення()
        +підтвердити замовлення()
        +позначити готовність()
    }

    class Відвідувач {
        -ім'я: String
        +сканувати меню()
        +зробити замовлення()
        +оплатити()
        +оцінити сервіс()
    }

    class Офіціант {
        -id: Int
        +підтвердити замовлення()
        +перевірити алергени()
    }

    class Шеф-кухар {
        -спеціалізація: String
        +позначитиГотовність()
    }

    class Замовлення {
        -id: Int
        -статус: String
        +додати позицію()
        +змінити статус()
    }

    class Позиція замовлення {
        -страва: String
        -кількість: Int
    }

    class Стіл {
        -номер: Int
    }

    class Сервіс оплати {
        +оплатити()
    }

    Учасник обслуговування <|-- Відвідувач
    Учасник обслуговування <|-- Офіціант
    Учасник обслуговування <|-- Шеф-кухар

    Відвідувач ..|> Бронювання
    Офіціант ..|> Бронювання
    Шеф-кухар ..|> Бронювання

    Замовлення o-- Позиція замовлення
    Стіл *-- Замовлення
    Замовлення ..> Сервіс оплати

    Відвідувач --> Замовлення : створює
    Офіціант --> Замовлення : підтверджує