stateDiagram-v2
    [*] --> Створене
    Створене --> Підтверджене: офіціант підтвердив
    Підтверджене --> У_приготуванні: передано на кухню
    У_приготуванні --> Готове: шеф-кухар позначив
    Готове --> Оплачене: відвідувач оплатив
    Оплачене --> Завершене: закрито
    Завершене --> [*]